### ISSUE TITLE
DO NOT DISABLE MY PVP MODS BECAUSE SOME GODDAMNED TIMER IN SOME PVE INSTANCE CHANGED

### ISSUE THREAD

**Issue by Vecht** [DeadlyBossMods/DeadlyBossMods#102]
Okay? Fuck off with this bullshit.

**Comment by MysticalOS** [comment]
https://classic.wowhead.com/news=303375/update-your-addons-wow-classic-threat-meters-switch-to-a-new-library

This pretty much spells out the importance of forced updates. the DBM updates push a new threat lib required to not only retain existing functions, but improve them with latest threat updates for classic. in fact,this update SPECIFICALLY fixes a very annoying but in battlegrounds where you'd get constant "you are not in a raid" spam in chat. that bug was caused by the old threat lib that the new threat lib fixes, so this update was more about fixing PVP than PVE
