### ISSUE TITLE
Add a 'whose loot is it' feature for classic?

### ISSUE THREAD

**Issue by mspk7305** [DeadlyBossMods/DeadlyBossMods#106]
The one phrase you hear over and over in MC is 'LOOT THE DOG'. There is an addon specifically for that type of thing right now but its something everyone needs to have... But DBM is something everyone needs to have and mostly do have already. So could a loot rights feature be added?

Please!?!

**Comment by MysticalOS** [comment]
This is not something that's going to be added to DBM Classic. it wouldn't be very reliable if users don't have mod, and i'd say classic adoption is still well under 50%. on top of that, it's really just not the place for DBM. maybe ORA or CTRaid or Leatrix would make more sense since these are addons more geared toward misc features such as that.

Also, this is not classic version of DBM but clearly version you meant
