### ISSUE TITLE
Can't disable blowhorn sound in Pandaria Remix (voice pack not always working)

### ISSUE THREAD

**Issue by brittyazel** [DeadlyBossMods/DeadlyBossMods#1106]
I keep getting an extremely loud blowhorn when doing Pandaria Remix dungeons and raids, and I can no longer find the "alerts" option to disable it like I used to. Is there a way to disable this blowhorn sound? It's extremely startling when it happens.

**Comment by MysticalOS** [comment]
is it airhorn sound? and when specifically is it played?

it's really hard for me to know where it's even used by default since by default DBM is using voice packs so I never hear the original sounds (except in some of the non updated raid bosses not modernized yet)

**Comment by brittyazel** [comment]
The first boss of heart of fear, on both Normal and Heroic. And yes it was the Airhorn sound. I'm also using the English Female voice pack, but it isn't working for me in Pandaria Remix (or at least not consistently). On Retail the voice pack works perfectly, this is just something to do with Remix.

**Comment by MysticalOS** [comment]
Yeah not all MoP raid bosses support it yet, which is why i needed clarification on where you hear horn. Been updating them slowly as time permits while also trying to fix cata classic issues and do war within prep.

This commit should pretty much address it though.
https://github.com/DeadlyBossMods/DBM-MoP/commit/490db02b9ffa24c60d22e63ddc5237651ff2838f

but in general you can also go into mod options and just change the sound to whatever you want.

**Comment by brittyazel** [comment]
Thank you. Can you be more specific on where I can find the setting in which to change the sound? I looked around for quite some time and could not find it.

**Comment by jungheeMW** [comment]
<img width="613" alt="dbm help" src="https://github.com/DeadlyBossMods/DeadlyBossMods/assets/134947146/330cdd1b-7047-471d-8f54-c18f4afd1a30">
If there are two drop down lists, the second. If there is only one, then that one.

**Comment by brittyazel** [comment]
Oh it's a per boss setting? I was looking under global settings to see if I could just swap the air horn for something else.

**Comment by MysticalOS** [comment]
it is also a global setting. if you dislike airhorn entirely then just change it globally instead of every mod
Also screen shot above has nothing to do with airhorn those menus change the countdown timer., you'd need to click sound one on special announcement
DBM guides are here:
https://github.com/DeadlyBossMods/DeadlyBossMods/wiki

**Comment by jungheeMW** [comment]
Oof, look at me embarrassing myself trying to help
