### ISSUE TITLE
Why it doesn't work for Chinese wlk?

### ISSUE THREAD

**Issue by qq61966100** [DeadlyBossMods/DeadlyBossMods#1137]
I can not use the dbm for chinese wlk version, it doesn't have WLK module.

**Comment by MysticalOS** [comment]
the WLK module separate download since the code is unified so every version of wow runs same mods, so you basically download Deadly Boss Mods + separate modules you need for game version you play. for you that'd be wrath mods (and optionally dungeons)
https://github.com/DeadlyBossMods/DeadlyBossMods/wiki/%5BNews%5D-DBM-Module-Restructuring-and-unification

**Comment by qq61966100** [comment]
@MysticalOS  Thanks, it works.

**Comment by Mini-Dragon** [comment]
@qq61966100 嘿，DBM需要下载核心模组、5人本模组和WLK的团本模组，都需要分开下载的。
