### ISSUE TITLE
UnitName error triggered by DBM-Raids-Dragonflight/VaultoftheIncarnates/KurogGrimtotem.lua

### ISSUE THREAD

**Issue by Farmbuyer** [DeadlyBossMods/DeadlyBossMods#1187]
Using the DBM-11.0.2 release from 28 July.  I vaguely remember this popping off well into the fight, but I couldn't tell you the exact situation.

```
1x Blizzard_UnitFrame/UnitFrame.lua:1114: bad argument #1 to 'UnitName' (Usage: local unitName, unitServer = UnitName(unit))
[string "=[C]"]: in function `UnitName'
[string "@Blizzard_UnitFrame/UnitFrame.lua"]:1114: in function <Blizzard_UnitFrame/UnitFrame.lua:1113>
[string "@DBM-Core/DBM-Core.lua"]:2858: in function `GetGroupId'
[string "@DBM-Core/DBM-Core.lua"]:7739: in function <DBM-Core/DBM-Core.lua:7736>
[string "=[C]"]: in function `sort'
[string "@DBM-Raids-Dragonflight/VaultoftheIncarnates/KurogGrimtotem.lua"]:441: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1046: in function <DBM-Core/DBM-Core.lua:1033>
[string "=(tail call)"]: ?
[string "@DBM-Core/DBM-Core.lua"]:1046: in function <DBM-Core/DBM-Core.lua:1033>

Locals:
InCombatSkipped

```

**Comment by MysticalOS** [comment]
This is probably being broken by this bug here: https://github.com/Stanzilla/WoWUIBugs/issues/631

which means it's best to wait it out cause blizzard is supposed to fix it by launch.

What's happening here is that mod attempts to set icon by sorted roster order, using names from combat log. The names in combat log are messed up right now so it passes names to the group sorter that it doesn't understand, and throws error.

**Comment by MysticalOS** [comment]
I'll leave issue open for tracking until blizzard confirms the underlying issue that's causing this error is resolved.

**Comment by MysticalOS** [comment]
made function more robust anyways so at least it'll silence error if running alpha
https://github.com/DeadlyBossMods/DeadlyBossMods/commit/4516a744f1e4199a090d3670639980c6d7ebc083

but the underlying cause, as I said, will also be be fixed blizzard soon™
