### ISSUE TITLE
Script ran to long

### ISSUE THREAD

**Issue by Cagomei** [DeadlyBossMods/DeadlyBossMods#1335]
2x DBM-Core/DBM-Core.lua:6650: script ran too long
[string "@DBM-Core/DBM-Core.lua"]:6650: in function `PlaySoundFile'
[string "@DBM-Core/modules/objects/Announce.lua"]:535: in function `Play'
[string "@DBM-Delves-WarWithin/TrashCommon.lua"]:223: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1080: in function <DBM-Core/DBM-Core.lua:1067>
[string "=(tail call)"]: ?
[string "@DBM-Core/DBM-Core.lua"]:1080: in function <DBM-Core/DBM-Core.lua:1067>

Locals:
self = <table> {
 DungeonMusic = <table> {
 }
 ReleaseRevision = 20241001000000
 TaintedByTests = false
 Arrow = <table> {
 }
 RangeCheck = <table> {
 }
 Test = <table> {
 }
 Voices = <table> {
 }
 BattleMusic = <table> {
 }
 InfoFrame = <table> {
 }
 Flash = <table> {
 }
 ModLists = <table> {
 }
 Difficulties = <table> {
 }
 Music = <table> {
 }
 classicSubVersion = 0
 HighestRelease = 20241001000000
 lastAntiSpamFLASH = 653549.680000
 registeredUnitEvents = <table> {
 }
 VoiceVersions = <table> {
 }
 AddOns = <table> {
 }
 Options = <table> {
 }
 Revision = 20241002234757
 Defeat = <table> {
 }
 DefaultOptions = <table> {
 }
 Victory = <table> {
 }
 Counts = <table> {
 }
 Nameplate = <table> {
 }
 HudMap = <table> {
 }
 DisplayVersion = "11.0.21"
 Mods = <table> {
 }
}
path = "Interface\AddOns\DBM-VPVEM\frontal.ogg"
ignoreSFX = nil
validate = nil
soundSetting = "Master"
(*temporary) = "Interface\AddOns\DBM-VPVEM\frontal.ogg"
(*temporary) = "Master"
(*temporary) = true
(*temporary) = 4673
(*temporary) = "script ran too long"
test = <table> {
 testRunning = false
 framesForTimeWarp = <table> {
 }
}

**Comment by MysticalOS** [comment]
this only happens if your disk took too long to respond to a playsound request. basically blizzard throws this error on their end if PlaySoundFile takes longer than 250 or 300ms to access file from disk. So for whatever reason your game or drive was unresponsive int his moment and it caused error. If playing wow on a HDD, it's suggested to use an SSD. if using an SSD, perhaps at that time windows was doing something that was causing performance degradation (maybe a system scan by virus scan/windows defender or something).

There is nothing we can do about it since blizzard is ones that control the script ran to long code (and honestly it's pretty crap code since it's totally uninformative to player of problem)
