### ISSUE TITLE
Broodtwister Ovi'nax red and purple raid icons are nearly impossible to see

### ISSUE THREAD

**Issue by miranda** [DeadlyBossMods/DeadlyBossMods#1337]
Problem:
The red X and purple diamond are nearly impossible to see against the red and purple environment.

Solution:
Would be great if these two could be changed to other icons, like orange circle and yellow star.

**Comment by MysticalOS** [comment]
the icons can be changed via drop down in menu by raid leader. the default icons I used made more sense and were easier to see, BUT I had to introduce those to match Bigwigs as the default for cross mod compatibility. That's why the default uses bigwigs configuration instead of mine. if raid leader is using DBm they can change it for whole raid, if they aren't then everyone would need to change icons individually to avoid conflicts (but if tehre are any bigwigs users in raid, there will be conflicts no matter what unless you use default option to match it)

**Comment by miranda** [comment]
What drop down are you referring to?  I relayed this information to the raid leader but he couldn't figure out where to change it.

**Comment by MysticalOS** [comment]
![Screenshot 2024-10-21 at 11 07 01 PM](https://github.com/user-attachments/assets/c3c1d547-ebfb-42cf-82af-c0bc8f119921)

**Comment by MysticalOS** [comment]
Looking at it, I may add the echo wigs mythic behavior as an all difficulty option too.
it's kinda funny that echo's version of BW coded in icons that specifically avoided diamond and X but it was never merged into public BW or really just adopted as default.

**Comment by miranda** [comment]
Thanks for the showing how to change it.  I guess people use the other addons so it's not possible for us to change it.  I can't believe the other addons picked such terrible colors.

Oh well.

**Comment by MysticalOS** [comment]
Yeah I did that purely for compat reasons but I didn't agree with their first choice, but it is what it is.

but I gave options if they were available.

**Comment by MysticalOS** [comment]
the last release added yet another option btw, as promised, but either way marking issue resolved as nothing more we can do on our end. at this point, as you said your raid uses mixed mods (much like mine does) so you're stuck using the Bigwigs compatible option default.
