### ISSUE TITLE
Variable timers at exactly the enlarge threshold behave oddly when being enlarged

### ISSUE THREAD

**Issue by emmericp** [DeadlyBossMods/DeadlyBossMods#1455]
Reproducer

```
foo = DBM:NewMod("Foo")
t = foo:NewCDTimer(123, "test")
t:Start("v10-20")
```

With enlarge threshold set to 10 seconds makes it starts out as large (good), but once it reaches 10 seconds remaining it seemingly tries to enlarge again and looks like a 5-10 variable timer.

![Screenshot 2024-12-21 125451](https://github.com/user-attachments/assets/a8e805f4-c972-4cd0-8a41-64144f18b927)

**Comment by emmericp** [comment]
Actually not specific to the threshold, it seems to be always incorrect once the "restart" as a 10 second large timer happens?

**Comment by Zidras** [comment]
Actually, this is exactly what I mentioned on Discord. On Classic anim, this repro case works flawlessly:

https://github.com/user-attachments/assets/a25ded64-d9e7-443d-92fe-123a75f40217

NoAnim however, misbehaves and since I encountered enlarge bugs with the DBT codebase prior to variance implementation, I left it alone and assigned it as unrelated (example shown below with bars resetting width, or fake enlarging when no large bars enabled, which also happened with variance code, and looked exactly like your bug, just with the enlarge large anchors enabled):

https://github.com/user-attachments/assets/44bb66a0-b2fd-4078-8940-4f76eb0410ef

I still think this is is a deeper bug than just the variance check inserted, but I'd have to take a deeper look into DBT... I haven't looked it at in a while

**Comment by Zidras** [comment]
Bug already described here: https://github.com/DeadlyBossMods/DBM-Unified/issues/135
