### ISSUE TITLE
DMB lua error, script ran too long

### ISSUE THREAD

**Issue by Gwills76** [DeadlyBossMods/DeadlyBossMods#1465]
2x DBM-Core/DBM-Core.lua:6743: script ran too long
[string "@DBM-Core/DBM-Core.lua"]:6743: in function `PlaySoundFile'
[string "@DBM-Core/modules/objects/Announce.lua"]:533: in function `Play'
[string "@DBM-Party-Cataclysm/ThroneOfTides/Ozumat.lua"]:207: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1069: in function <DBM-Core/DBM-Core.lua:1055>
[string "=(tail call)"]: ?
[string "@DBM-Core/DBM-Core.lua"]:1069: in function <DBM-Core/DBM-Core.lua:1055>

**Comment by MysticalOS** [comment]
this happens when PC/disk lags, nothing DBM can do about it. blizzard just POORLY handles the code for media playback. if it takes longer than 250ms to load the media from disk, it fails with this error.

maybe antivirus was running, maybe windows update was, but in that moment your disk didn't respond fast enough and blizzard blamed DBM for it.

**Comment by Gwills76** [comment]
Is there a easy way to potentially solve this issue?

**Comment by MysticalOS** [comment]
Nope. if you aren't using an SSD, you def should be. otherwise nope.

**Comment by Gwills76** [comment]
Alrighty thank you so much!
