### ISSUE TITLE
Mythic Uu'nat Unstable Resonance and Shadow Priest

### ISSUE THREAD

**Issue by Arkilyte** [DeadlyBossMods/DeadlyBossMods#17]
On Mythic Uu'nat if you are in voidform as a shadow priest the /yell (/say) will not work for unstable resonance. If you are not in voidform it works.

**Comment by MysticalOS** [comment]
That's because there is nothing I can do about it. if i spammed a yell it'd be useless. you think the priest repeatedly saying "zagna cthulu" over and over again would provide useful information to raid? I feel it's better to mute it than add useless noise.

Position yells and countdown yells are muted on priests in void form. APPLIED yells for things where the point of yell is to see position of player at time of application, are not muted. As such, for unstable you should see an application yell initially but the icon spam yells are disabled since there would be no icon.

**Comment by Arkilyte** [comment]
There is no application yell, and being able to see the whole raid's chat bubbles and then someone trying to move around them without a chat bubble seems detrimental.
