### ISSUE TITLE
DBM Pull-Timer Bugged

### ISSUE THREAD

**Issue by OdessaGrimaldus** [DeadlyBossMods/DeadlyBossMods#370]
**Twitch client installed classic/retail version on retail/classic**
|
Twitch Client download, Retail on Retail.

**Describe the bug**
|
At the beginning of a a mythic+ dungeon, with a 10 second pull-timer actively counting down for the key to be put in.. ..when the key was activated and I came off the loading screen the countdown timer that came was a 25 second timer, when it has always been a 10 second pull, counting down the shield drops, and remained there even post the dungeon beginning, counting down until it concluded.

**Do you have an error log of what happened?**
|
I do not, there was no actual error produced by this bug.

**To Reproduce**
|
Simply set a pull-timer, and activate a key for a mythic+ instance's beginning and the concluding pull-timer gets added to the 10 second "mythic dungeon beginning" countdown.

**Screenshots**
|
I do not have any.

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**
|
Currently I am using - "9.0.1." Release version.

**Was it working in a previous version? If yes, which was the last good one?**
|
I had no issues with any version back before the updates began for the 9.0 patch drop.

**Additional context**

**Comment by MysticalOS** [comment]
I have theory on cause, it's code on blizzards end more than DBMs that simply caused the actual M+ timer not to start, where the 25 came from is still a mystery, maybe another blizzard bug, or maybe DBM trolling. EIther way I added protections against DBM trolling (using DBM to override a blizzard started timer) as well as failsafe that if the DBM pull timer isn't complete at time of keystone activation, it's cleared so that the M+ timer is allowed to run.

Try latest alpha and see if issue persists.

**Comment by OdessaGrimaldus** [comment]
Thank you, Mystical. I will do just that and get back to you.

**Comment by MysticalOS** [comment]
It's actualy a blizzard bug so I'm going to be closing this. DBM is not doing that. The work arounds I put in were to fix something else entirely where DBM might prevent the blizzard timer from starting all together, but it starting with an invalid time, that is something they just broke in 9.0.
