### ISSUE TITLE
Problem in M+ Dungeons and Raids! 

### ISSUE THREAD

**Issue by Paradox3008** [DeadlyBossMods/DeadlyBossMods#372]
Hey Guys. 

I use the actuell Version of DBM.  And I'm using ELVUI like a lot of my Guild Members too. 

So my Problem is (And i am the only one with this Problem), that at the start of an M+ Dungoen, after the stone is placed.. i got a little bar at the top of my Screen with a Countdown of 2:45 or 3:00 minutes. And if the Timer reaches 1:30 it turns into Seconds. That counting down like a pull Timer, in a very big scaling in the middle of my Screen with the sound like a Pull Timer.. And that is very very very annoying. I dont have any Screenshots yet.. Cause i tried to fix it on my own. But no one started a regular Pull Timer...!!

Can u guys help me? 

If you need further informations tell me! 

P.S. My English is not the best. SOrry for some Mistakes in my Text.

Have a great day!

**Comment by MysticalOS** [comment]
Not caused by DBM, this appears to be a new blizzard bug, happens to users not using DBM at all, even users with no addons. Blizzard just sends an invalid time argument with START_TIMER in M+ since prepatch.

**Comment by nivthefox** [comment]
@MysticalOS So just as a bit of added context, I have this problem as well.  My countdown starts at 1:50 every time I pull M+; however, when I disable DBM, this problem goes away.  Are you sure there's no problem with DBM, at all, here?

**Comment by MysticalOS** [comment]
There are literally users on forum that have no addons installed, or are using bigwigs, NOT dbm having issue. this is not caused by DBM. the only parallel to DBM is DBM also uses the countdown feature for pull timers in a separate way that would have no affect on the M+ timer. Of course people draw that parallel and think DBM is breaking the M+ timer. DBM didn't start using the countdown object yesterday, it's been using it since it was added to game, lik 4 ot 5 years ago. M+ timer worked throughout legion and throughout BfA, it broke in 9.0 prep patch on blizzards end in some form or another.

**Comment by nivthefox** [comment]
I understand that; however, the problem does go away when I disable DBM. I'm not making an accusation, I'm just trying to provide information in the hopes that it will help you double check.  If I continued to have this problem when I disabled DBM, I'd agree 100% DBM has nothing to do with this.  As is, since you seem a bit incensed, I'll stand down until Blizzard says they've fixed it.  I just wanted to provide a different bit of insight.

**Comment by MysticalOS** [comment]
What I suspect is actually breaking on blizzards end, is the mythic+ timer specifically breaks after the START_TIMER object has started another timer earlier in session. Having DBM installed might cuse it to break faster, but isn't the cause of the break. As I said users not using DBM can still see the bug. I'm willing to bet if a user jumped into a BG and then a M+, or did some /countdown timers it'd be very much still have a broken M+ timer.

In any case, I completely removed the feature from DBM because I'm tired of dealing with it and the feature will not be returning to DBM unless blizzard fixes their bug. When users still complain about it (and they will) I'll at least be able to show them that.

**Comment by Paradox3008** [comment]
Hey guys. 
I still have the Problem too. 
But as an Information. I wrote blizzard and they told me, that they have heard from some users, that have the same Problem. 
But the thing is. If the other player also use DBM why doenst have all Player the same Problem. I am the only one in my guild. 
And i didnt change anything in DBM for example just the position of the Bars.

**Comment by meia120** [comment]
As you know, I also have this problem - just to be clear, we are saying that it is simply a bug on blizzard's part and we wait for it to be fixed? Thanks!

**Comment by QartemisT** [comment]
Yes, it is a blizzard bug, and its their problem to fix :)

**Comment by meia120** [comment]
Okay thanks a lot :)
