### ISSUE TITLE
Been getting this error

### ISSUE THREAD

**Issue by ghodhereek** [DeadlyBossMods/DeadlyBossMods#4]
**Describe the bug**

**Do you have an error log of what happened?**
Date: 2019-04-24 21:10:13
ID: 1
Error occured in: Global
Count: 1
Message: integer overflow attempting to store 20190424000000
Debug:
   [C]: format()
   DBM-Core\DBM-Core.lua:4522:
      DBM-Core\DBM-Core.lua:4493
   DBM-Core\DBM-Core.lua:4591:
      DBM-Core\DBM-Core.lua:4581
   (tail call): ?
   DBM-Core\DBM-Core.lua:5102: handler()
   DBM-Core\DBM-Core.lua:695:
      DBM-Core\DBM-Core.lua:682
Locals:
(*temporary) = " Version %s (r%d) is available for download through Curse/Twitch, WoWI, or from deadlybossmods.com"
(*temporary) = "8.1.20"
(*temporary) = 20190424000000

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
This is fixed in 8.1.20, you'll just see the error when running 8.1.19 version and getting the sync telling you 8.1.20 is available. Update and you won't see it again, and when future versions come out, you won't get errors from the notifications.

**Comment by ghodhereek** [comment]
I had my Twitch/Curse client in auto update for my DBM. I guess I have to get it manually.

**Comment by MysticalOS** [comment]
twitch client is utterly hosed, it does not auto refresh or auto update worth a damn since new interface. It literally only works best on fresh launch. The best way to use it now. open it, update addons, then EXIT it (not minimize or hide, CLOSED). fresh launch it next time you login to wow to grab fresh updates.

Refresh, auto update don't work worth a crap. I've been seeing lots of users relying on twitch client to work correctly, end up with out of date addons as a result. Their new client is crap, they should never have released it and kept the older actually working one until this one was ready. Sadly, they didn't.
