### ISSUE TITLE
Ashvane upsurge timer is inaccurate in mythic

### ISSUE THREAD

**Issue by Elnarfim** [DeadlyBossMods/DeadlyBossMods#46]
**Describe the bug**
2, 3 phase timer is inaccurate except first one. approx. 1 sec

**Do you have an error log of what happened?**
[https://drive.google.com/file/d/1CLnfWcb5yyBo7byqVb4zrJkVXFHMnKv8/view?usp=sharing](url)

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
I reviewed timers for upsurge and found no issues. My findings were exactly same as original ones. the correct minimum times are used. 29.9 and 14.9.

yes sometimes it's 30.4 or 30.8 or something, but that's just standard variation. but coding in 30.8 means it'd be wrong every time it's 29.9.

**Comment by MysticalOS** [comment]
The shield timer is also 70.5-71.8 variation. that's the worse offender. but that's not wrong either. Because her shield is based on an energy timer, it's subject to being worse beause blizzard energy based timers are notoriously bad/inaccurate. Just about every timer in game that's for an energy timer has a 1-2 second variation minimum do to fact blizzards energy code is crappy and uses some non time accuate onupdate tick that makes something that's SUPPOSED to be consistent, deviate a little.

**Comment by Elnarfim** [comment]
I understand it. Thanks for answer :)
