### ISSUE TITLE
NPC Talking Heads frame permanently disabled

### ISSUE THREAD

**Issue by TheCheat54** [DeadlyBossMods/DeadlyBossMods#485]
DBM is permanently disabling the NPC dialogue talking head frame regardless of the setting in the Filter->Blizzard Features menu or boss combat status. I was able to narrow this down to have changed in version 9.0.17-34-g14fb467.

If I revert to 9.0.17-33-gd002daf, the functionality is restored.

Also note that I originally noticed the issue after updating to 9.0.18-1-g0125762 earlier today and re-confirmed in 9.0.18-2-g1fee77a.

EDIT: Even in 17-33 it seems highly inconsistent. However, disabling DBM Core restores 100% functionality.

**Comment by MysticalOS** [comment]
DBM doesn't even touch talking head, at all. This is likely another addon doing this.

**Comment by MysticalOS** [comment]
that functionality hides a totally unrelated frame and only during boss fights. Talking head isn't touched by dbm at all, might wnat to check if another addon is either hiding or maybe tainting it by misusing an element talking head uses (which would then cause it to stop working until you reloadui, and since disabling dbm reloaded ui it gave illusion disabling dbm solved it, when all you did was cleared tainted execution path another addon caused)

**Comment by TheCheat54** [comment]
You're right, it might actually be. My only other recent update has a report from today about an issue related to the frame but that addon hasn't thrown any LUA errors on my client. I'm just going to revert it and deal for now, apologies for the misdirected report.
