### ISSUE TITLE
Timer Bug on Council of Blood

### ISSUE THREAD

**Issue by korruption94** [DeadlyBossMods/DeadlyBossMods#510]
With the newest version of DBM that was released today, I began experiencing an issue with the timers for Council of Blood as you can see https://clips.twitch.tv/RelatedFitRadicchioFeelsBadMan-SWD4WX6MgP0HSnym here. Timers begin for mechanics that aren't even supposed to happen at this point in the fight (Stavros and Niklaus both alive but shows a timer for Castellan Cadre), as well as desyncing the timers for every other mechanic in the fight. I was able to reinstall the previous version of the add-on for it to fix.

**Comment by QartemisT** [comment]
Version released today? Can you explain this.

As 9.0.19 was released 20 days ago, so unless you can point us a specific version number that would be useful.
Thanks.

**Comment by korruption94** [comment]
Yes, I updated my add-on through Curseforge today and have been using that to update my add-ons for over a month multiple times a week, I thought the newest version came out today. It is version 9.0.19. Version 9.0.18 has the appropriate timers with no errors.

**Comment by QartemisT** [comment]
There have only been two changes between 9.0.18 and 9.0.19, neither of which have even touched timers at all. Are you completely sure 9.0.18 is working properly?

https://github.com/DeadlyBossMods/DeadlyBossMods/commits/master/DBM-CastleNathria/TheCouncilofBlood.lua?since=2021-01-19T15:30:04Z&until=2021-01-27T05:31:42Z

**Comment by korruption94** [comment]
Across my guild's first 50 pulls of the boss, there were no timer issues using 9.0.18 but after updating today, multiple pulls had issues with the timers not being correct before I reverted to the previous version and no longer had those timer issues. You can see from the clip I linked above, or the vod https://www.twitch.tv/videos/915659957?t=3h3m19s here that for two or three pulls, the timers get messed up when we have a Dark Recital and kill Baroness Frieda during it. That seems to be what is causing it, but I'm not certain.

**Comment by MysticalOS** [comment]
There is a blizzard bug where sometimes on phase change the event for the phase change doesn't happen, when this happens it doesn't just bug DBM it actualy bugs fight itself. timers that are supposed to restart do not.

DBM is coded to always assume the fight works correctly so sometimes when the timers fail to restart do to the blizz bug, the dbm timers will be wrong, because I just didn't feel like coding special rules for a blizz bug I reported and hoped they'd fix (they didn't as far as know).

But as QartemisT says, there haven't been any changes to that fight between .18 and .19. you probably just consistently triggered blizzards bug a few pulls, and then stopped triggering it by pure coincidence when you rolled back.

**Comment by MysticalOS** [comment]
OH, you're using the pho weak aura. that will break the hell out of timers actually because it hasn't been updated since 2019 and doesn't support all the addtime/remove time methods

**Comment by MysticalOS** [comment]
For good measure I made phase change code a little more robust to try and prevent situations it maybe got increased twice at same time though.

**Comment by MysticalOS** [comment]
Fixed in .21 btw
