### ISSUE TITLE
Dark Recital of Afterimage of Lord Stavros doesn't warned

### ISSUE THREAD

**Issue by patrickwu1991** [DeadlyBossMods/DeadlyBossMods#526]
During the fight in mythic, I found the timer for Dark Recital casted by Afterimage of Lord Stavros did not trigger warning sfx.
Not sure if the spellID in dead script is wrong, it uses 331635 instead of 331634 which shared by living/dead version of Lord Stavros.

**Comment by MysticalOS** [comment]
Probably got the timer bug where it didn't appear. nothing is wrong iwth trigger. 331635 is a dummy spellid that's literally just for holding the after images timers in a different table. Both actualy trigger off 331634. It's likely the timer had an anchor error and didn't show because of that. Try latest alpha to see if that resolves it. Gonna close this though as it's invalid. I'm very confident you got https://github.com/DeadlyBossMods/DeadlyBossMods/issues/506
