### ISSUE TITLE
recent update

### ISSUE THREAD

**Issue by Drcox777** [DeadlyBossMods/DeadlyBossMods#646]
when i try to update to the new version windows defender freaks out says there is a script running and then says there is a trojan never had this happen before

**Comment by MysticalOS** [comment]
i can't imagine that's still the case, you reporting about something that happened 12 hours ago? it was already fixed by microsoft on offending file AND for good measure a new release was made that never got improperly flagged.

either way closing this as duplicate of https://github.com/DeadlyBossMods/DeadlyBossMods/issues/645 and https://github.com/DeadlyBossMods/DeadlyBossMods/issues/643

**Comment by Drcox777** [comment]
this is right now man i am trying to update right now

**Comment by MysticalOS** [comment]
what updater? what file? what antivirus? because it only affected 9.1.9 and 9.1.10 is latest.

**Comment by Drcox777** [comment]
using curseforge on overwolf, i have 9.1.9 installed and i am trying to update to the new version, maybe if i remove the old version all together?

**Comment by Drcox777** [comment]
it only happens when i try to update though so thats confusing

**Comment by MysticalOS** [comment]
so you're saying 9.1.10 is also flagged as malware?

**Comment by Drcox777** [comment]
it would appear so

**Comment by Drcox777** [comment]
and now its magically fixed

**Comment by Drcox777** [comment]
well if i wasted your time sorry, ty for your help

**Comment by MysticalOS** [comment]
i def want to know if 9.1.10 is also flagged. it's more than likely you still had a cached 9.1.9 file in downloads cache

**Comment by MysticalOS** [comment]
neither file had malware by teh way, microsoft falsely flagged it and already fixedd it on server side but on client side requires resetting cache or getting a new definition update

https://cdn.discordapp.com/attachments/877534431026511934/877653019024584774/unknown.png
