### ISSUE TITLE
Updating through Twitch client installs classic version

### ISSUE THREAD

**Issue by otmeek** [DeadlyBossMods/DeadlyBossMods#82]
I was notified that DBM was out of date today, and updated it through Twitch client. However when I booted wow back up I get an error saying that I am using the classic version of DBM.

I downloaded the zip from github directly and it is the correct version, however Twitch will detect it and list it as out of date. Upon updating it will again replace it with the classic version and notify me that I am using an incorrect version.

The version I am using without the error is 8.2.24-10-g99af0dd
The latest version according to twitch is 1.13.17-4-g01e8611-classic
Which should I be using on retail?

**Comment by MysticalOS** [comment]
8.x should be retail. the classic version is even labeled with -classic

I have no idea why some users get this problem with twitch client, as I use it to update retail, ptr and classic with 0 issues. It's never once installed wrong mod version for the client i told it to update. The annoying thnig apart is that everyone reports issues to addon authors and no one is contacting twitch (mostly because they make it difficult TO contact them). As such, I doubt twitch even knows it's happening or why.

I can tell you that there is NOTHING addon authors can do, so i'll be closing this ticket, and just referring it with https://github.com/DeadlyBossMods/DeadlyBossMods/issues/74 like rest of these.
