### ISSUE TITLE
a few Soundkit IDs broken

### ISSUE THREAD

**Issue by Invisybr** [DeadlyBossMods/DeadlyBossMods#89]
**Describe the bug**
a couple of the sounds are missing from the special warnings

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes

**Which version of DeadlyBossMods are you using?**
8.2.29 alpha

**Was it working in a previous version? If yes, which was the last good one?**
Yes, I assume prior to wow 8.2

**Additional context**
So I noticed a couple of the special warnings I liked were missing after a break from the game, I spent a little bit digging around to see if I could fix the issue myself, as some of the sound files were still available to me in weakauras but not dbm, and there were no .ogg files I could find. I'm not super familiar with this, but it seems that maybe the file paths were changed in 8.2 as I was able to find a list for a fix on a similar issue for the omen addon. Looking at the list they posted, everything in it is also missing from DBM with the exception of c'thuun "you will die".

You can find the list here in case it helps:
https://www.wowace.com/projects/omen-threat-meter/issues/114

**Comment by MysticalOS** [comment]
DBM doesn't support playing sounds through file data Ids, which is what those examples use.

it was a choice I made to maintain parady with classic which does NOT support the 8.2 sound channels. Classic is based on 8.1.5.

DBM only supports sound from libsharedmedia registered as a path(ie custom sounds in addon folder). DBM rejects all file data Id based sounds. Internally DBM also registers several of it's own media paths using soundkit (not file data id) since soundkit is compatible with both 8.1.5 (ie classic) and 8.2+ (retail).

This is why some LSM sounds are missing.

Now, DBM did have a bug where some build in sounds had bad copy and paste soundkit Ids, this is fixed in current alpha though.
