### ISSUE TITLE
I change the Level 3 warning to a different sound, but it still just plays the stupid Airhorn

### ISSUE THREAD

**Issue by MattLyte** [DeadlyBossMods/DeadlyBossMods#93]
Really don't know what to say. I can't figure out why it plays the airhorn at all, because I changed the level 3 warning to Algalon's "Beware", and I hear that during fights. I also hear the level 1, 2, 4 and 5 warnings that I have set, but continue to hear the airhorn for things like Gaze from Below on Blackwater Behemoth. I can't figure out why it still plays the airhorn, but I won't be able to keep dbm installed if I can't turn this airhorn off, so please assist if you can.

I can attempt to provide further info on exactly which events cause it to play, but I would first need to know which events to look for, as the boss fights as a whole are still too new to me for me to be able to just sit and watch everything without causing a wipe over and over.

**Comment by MysticalOS** [comment]
1. check for any redundant weak auras that also have an airhorn
2. i strongly suggest NOT setting special awrning type 3 to same sound 2s use, you can't etll them apart them. if you don't like air horn at least make it a diff sound than what 2 uses. 
3. if you only change it on specific warning instead of globally, then it's only changed for THAT warning and not rest of them still using SW3.

closing ticket because tickets is not how you do support. you generally come to discord for actual support. this is for bug/issue tracking with dbm.
