### ISSUE TITLE
DBM steals the /countdown command

### ISSUE THREAD

**Issue by ptarjan** [DeadlyBossMods/DeadlyBossMods#950]
**Describe the bug**
I use `/countdown 10` to start a timer. All users of DBM and bigwigs see it, users without those addons do no see it.

**Do you have an error log of what happened?**
No error

**To Reproduce**
1. Create a group with a wow player who doesn't have DBM
2. Type `/countdown 10` as the leader
3. Have them not see anything

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of DeadlyBossMods are you using?**
10.2.5

**Was it working in a previous version? If yes, which was the last good one?**
Yes. The only member of our raid who doesn't use DBM last played about 3 months ago with us, so it broke sometime between then and now.

**Additional context**

**Comment by MysticalOS** [comment]
That's intended. both DBM and BW replace blizzards countdown because it's just bad and insecure. People who refuse to install either addon really shouldn't be catered to at higher levels of raid and M+, and as for LFR and even normal to an extent, it's less important.

**Comment by ptarjan** [comment]
Thanks for explaining. I do see your point and very much ask all my group members to install DBM, but some folks just won’t, for various reasons. There is an alternative that you folks used before, being /pull. I’d much prefer if you could just use that command for your countdown and still leave the game-internal one for /countdown. Then users have a choice of which they want to use, right now I have no way of sending the in-game one.

**Comment by Morvinthones** [comment]
> That's intended. both DBM and BW replace blizzards countdown because it's just bad and insecure. People who refuse to install either addon really shouldn't be catered to at higher levels of raid and M+, and as for LFR and even normal to an extent, it's less important.

Your argument is inconsistent. At higher levels of play groups are going to tend to be mostly static where concerns of """"security"""" are less of an issue. And where, frankly, if someone with assist in a raid is throwing up false countdown timers that is probably an indication of other issues that would need to be addressed regardless. Moreover, in a higher end group, maybe it should be up to the group to decide on whether or not to require DBM/BigWigs? In lower end play, there should be a way to do a countdown that communicates to players that don't have either addon installed. 

Also, in M+, only the leader can do a blizzard countdown so the the question of who did the countdown is reflexively answered.

Perhaps stealing the /cd command could only be enabled in a raid group? Or maybe include an option to countdown into chat?

**Comment by ptarjan** [comment]
Thanks for the reply. I'm not quite sure how my argument is inconsistent. My guild is a heroic raiding guild who has gotten AotC for every raid since the start of the game, so I hope we hit your level of "higher end group". 

My use case is I, as the tank, want to start a countdown to attack a boss, so I type `/countdown 10`. I have DBM installed but one of my raid members chooses to not have DBM installed. With the newly changed implementation that member will not see any countdown whatsoever whereas in the previous raid tier they did. I would like them to see the countdown and my preference is it to appear identical to the inbuilt `/countdown`. Can I somehow do that?

**Comment by Morvinthones** [comment]
Ptarjan, I'm on your side. I also play in a regular mixed group (M+ instead of raiding), and it is annoying to have to make sure that DBM users don't have lead so non-users can get a proper countdown for pre-potting.

My quoting of MysticalOS's comment was intended to indicate I was replying to them. Not knowing who initiated a countdown is mostly a concern in pickup groups and LFR, and yet this change was implemented for high-end players who are largely going to have static groups? DBM is among the most popular addons in the game, but most of its users (that is, "lower end" players) are beneath consideration? Allowing DBM users to have a countdown that non-users of the addon can see isn't catering to non-users, capturing the /cd command is actively hostile to non-users, and depending on the context it is also hostile to users of the addon.

**Comment by MysticalOS** [comment]
It was a collective decision by bigwigs and DBM both to blocks blizzards function because of their failure to address numerous issues we reported with it. You keep saying high end but if a player is playing "high end" with neither DBM or BW, chances are they don't belong there cause they're holding the group back. And yes most of the issues are with pugs and pugs are a big part of M+ believe it or not. But any high key, or heroic or higher raid should be on DBM or BW and if they're not they should probably be forced to get either mod or removed from group.

So yes, both mods replace inferior solution with superior one that actually does have users best interest at heart since it uses better security, and better implementation, and actually works in all game versions (try that /countdown command in wow classic). We'd rather establish a working standard across all content difficulties and game versions with a full feature set and not a half assed one like blizzard countdown. If blizzard were to take even half our feedback, not only would we use theirs instead, but we'd make it the default entirely and simply add our enhancements on top of their framework. Until such a time, we will both continue to replace it with our own that's more robust.

**Comment by ptarjan** [comment]
Could you link me to your feedback discussion with blizzard please? It would be helpful for me to see your and their reasoning.

As for standard, why can’t you standardize on /pull as you did for many years? Or barring that at least give me the option to disable this override?

**Comment by Morvinthones** [comment]
You seem to have forgotten that group content is dependent on the performance of the group. When DBM captures /cd, and does not even minimally provide an alternative output (such as chat) for players that do not have the addon, it is not just impairing the non-users, it is impairing the users of the addon by reducing group performance. You may hate the very idea of pugging 20s with people that aren't using a boss addon, but if you pug 20s, you are going to play with those players, and impairing countdown communication with those players is only going to reduce your chances of timing the key.

I have done low 20s keys with people that don't use boss addons, and they are often not the weak link in the group. Just assuming those players are bad, and expressing they shouldn't do that content is frankly pretty off-putting to read.

You and the other developers of DBM and BW have made a decision about how not just users of these addons engage with the game, but also non-users. I'm sorry Blizzard isn't treating the usage of /cd the way you all want them to. Attempting to hold the community hostage over it, and acting like you are doing everyone a favor seems irrational to me, an outsider.

Your opinions about how other people play the game are pretty extreme; I doubt any rational argument will cause you to re-allow usage of Blizzard's /cd. However, BW allows outputting the countdown into a chat channel. Could you all at least enable this as an option in DBM as well?
